/** National Archives transcription of the Stone Engraving of the Declaration of Independence.
 *  https://www.archives.gov/founding-docs/declaration-transcript
 *  Spelling and punctuation follow that transcript. Labels are not the legal text.
 */

export const declaration = {
  id: "declaration",
  title: "The Declaration of Independence",
  short: "Declaration",
  year: "1776",
  blurb: "One self-evident truth, one grievance, one pledge — never the whole parchment at once.",
  source: "https://www.archives.gov/founding-docs/declaration-transcript",
  sourceLabel: "National Archives transcription",
  bites: [
    {
      id: "heading",
      kind: "heading",
      group: "Opening",
      cite: "Heading",
      label: "In Congress",
      text: "In Congress, July 4, 1776.\n\nThe unanimous Declaration of the thirteen united States of America,",
    },
    {
      id: "opening",
      kind: "clause",
      group: "Opening",
      cite: "Opening",
      label: "When in the Course of human events",
      text: "When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.",
    },
    {
      id: "truth-equal",
      kind: "truth",
      group: "Self-evident truths",
      cite: "Self-evident truth 1",
      label: "Created equal",
      text: "We hold these truths to be self-evident, that all men are created equal,",
    },
    {
      id: "truth-rights",
      kind: "truth",
      group: "Self-evident truths",
      cite: "Self-evident truth 2",
      label: "Unalienable Rights",
      text: "that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.",
    },
    {
      id: "truth-government",
      kind: "truth",
      group: "Self-evident truths",
      cite: "Self-evident truth 3",
      label: "Consent of the governed",
      text: "--That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed,",
    },
    {
      id: "truth-alter",
      kind: "truth",
      group: "Self-evident truths",
      cite: "Self-evident truth 4",
      label: "Right to alter or abolish",
      text: "--That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness.",
    },
    {
      id: "prudence",
      kind: "clause",
      group: "Self-evident truths",
      cite: "Prudence",
      label: "Not for light and transient causes",
      text: "Prudence, indeed, will dictate that Governments long established should not be changed for light and transient causes; and accordingly all experience hath shewn, that mankind are more disposed to suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they are accustomed.",
    },
    {
      id: "duty",
      kind: "clause",
      group: "Self-evident truths",
      cite: "Duty",
      label: "A long train of abuses",
      text: "But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.",
    },
    {
      id: "necessity",
      kind: "clause",
      group: "Self-evident truths",
      cite: "Necessity",
      label: "Facts submitted to a candid world",
      text: "Such has been the patient sufferance of these Colonies; and such is now the necessity which constrains them to alter their former Systems of Government. The history of the present King of Great Britain is a history of repeated injuries and usurpations, all having in direct object the establishment of an absolute Tyranny over these States. To prove this, let Facts be submitted to a candid world.",
    },
    {
      id: "grievance-01",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 1",
      label: "Assent to Laws",
      text: "He has refused his Assent to Laws, the most wholesome and necessary for the public good.",
    },
    {
      id: "grievance-02",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 2",
      label: "Governors forbidden to pass Laws",
      text: "He has forbidden his Governors to pass Laws of immediate and pressing importance, unless suspended in their operation till his Assent should be obtained; and when so suspended, he has utterly neglected to attend to them.",
    },
    {
      id: "grievance-03",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 3",
      label: "Representation in the Legislature",
      text: "He has refused to pass other Laws for the accommodation of large districts of people, unless those people would relinquish the right of Representation in the Legislature, a right inestimable to them and formidable to tyrants only.",
    },
    {
      id: "grievance-04",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 4",
      label: "Unusual places of assembly",
      text: "He has called together legislative bodies at places unusual, uncomfortable, and distant from the depository of their public Records, for the sole purpose of fatiguing them into compliance with his measures.",
    },
    {
      id: "grievance-05",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 5",
      label: "Dissolved Representative Houses",
      text: "He has dissolved Representative Houses repeatedly, for opposing with manly firmness his invasions on the rights of the people.",
    },
    {
      id: "grievance-06",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 6",
      label: "Refused new elections",
      text: "He has refused for a long time, after such dissolutions, to cause others to be elected; whereby the Legislative powers, incapable of Annihilation, have returned to the People at large for their exercise; the State remaining in the mean time exposed to all the dangers of invasion from without, and convulsions within.",
    },
    {
      id: "grievance-07",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 7",
      label: "Obstructed population",
      text: "He has endeavoured to prevent the population of these States; for that purpose obstructing the Laws for Naturalization of Foreigners; refusing to pass others to encourage their migrations hither, and raising the conditions of new Appropriations of Lands.",
    },
    {
      id: "grievance-08",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 8",
      label: "Administration of Justice",
      text: "He has obstructed the Administration of Justice, by refusing his Assent to Laws for establishing Judiciary powers.",
    },
    {
      id: "grievance-09",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 9",
      label: "Judges dependent on his Will",
      text: "He has made Judges dependent on his Will alone, for the tenure of their offices, and the amount and payment of their salaries.",
    },
    {
      id: "grievance-10",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 10",
      label: "New Offices and swarms of Officers",
      text: "He has erected a multitude of New Offices, and sent hither swarms of Officers to harrass our people, and eat out their substance.",
    },
    {
      id: "grievance-11",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 11",
      label: "Standing Armies",
      text: "He has kept among us, in times of peace, Standing Armies without the Consent of our legislatures.",
    },
    {
      id: "grievance-12",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 12",
      label: "Military above Civil power",
      text: "He has affected to render the Military independent of and superior to the Civil power.",
    },
    {
      id: "grievance-13",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 13",
      label: "Foreign jurisdiction",
      text: "He has combined with others to subject us to a jurisdiction foreign to our constitution, and unacknowledged by our laws; giving his Assent to their Acts of pretended Legislation:",
    },
    {
      id: "grievance-14",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 14",
      label: "Quartering troops",
      text: "For Quartering large bodies of armed troops among us:",
    },
    {
      id: "grievance-15",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 15",
      label: "Mock Trial",
      text: "For protecting them, by a mock Trial, from punishment for any Murders which they should commit on the Inhabitants of these States:",
    },
    {
      id: "grievance-16",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 16",
      label: "Cutting off Trade",
      text: "For cutting off our Trade with all parts of the world:",
    },
    {
      id: "grievance-17",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 17",
      label: "Taxes without Consent",
      text: "For imposing Taxes on us without our Consent:",
    },
    {
      id: "grievance-18",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 18",
      label: "Trial by Jury",
      text: "For depriving us in many cases, of the benefits of Trial by Jury:",
    },
    {
      id: "grievance-19",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 19",
      label: "Tried beyond Seas",
      text: "For transporting us beyond Seas to be tried for pretended offences:",
    },
    {
      id: "grievance-20",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 20",
      label: "A neighbouring Province",
      text: "For abolishing the free System of English Laws in a neighbouring Province, establishing therein an Arbitrary government, and enlarging its Boundaries so as to render it at once an example and fit instrument for introducing the same absolute rule into these Colonies:",
    },
    {
      id: "grievance-21",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 21",
      label: "Taking away Charters",
      text: "For taking away our Charters, abolishing our most valuable Laws, and altering fundamentally the Forms of our Governments:",
    },
    {
      id: "grievance-22",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 22",
      label: "Suspending Legislatures",
      text: "For suspending our own Legislatures, and declaring themselves invested with power to legislate for us in all cases whatsoever.",
    },
    {
      id: "grievance-23",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 23",
      label: "Abdicated Government",
      text: "He has abdicated Government here, by declaring us out of his Protection and waging War against us.",
    },
    {
      id: "grievance-24",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 24",
      label: "Plundered our seas",
      text: "He has plundered our seas, ravaged our Coasts, burnt our towns, and destroyed the lives of our people.",
    },
    {
      id: "grievance-25",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 25",
      label: "Foreign Mercenaries",
      text: "He is at this time transporting large Armies of foreign Mercenaries to compleat the works of death, desolation and tyranny, already begun with circumstances of Cruelty & perfidy scarcely paralleled in the most barbarous ages, and totally unworthy the Head of a civilized nation.",
    },
    {
      id: "grievance-26",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 26",
      label: "Captives on the high Seas",
      text: "He has constrained our fellow Citizens taken Captive on the high Seas to bear Arms against their Country, to become the executioners of their friends and Brethren, or to fall themselves by their Hands.",
    },
    {
      id: "grievance-27",
      kind: "grievance",
      group: "Grievances",
      cite: "Grievance 27",
      label: "Domestic insurrections",
      text: "He has excited domestic insurrections amongst us, and has endeavoured to bring on the inhabitants of our frontiers, the merciless Indian Savages, whose known rule of warfare, is an undistinguished destruction of all ages, sexes and conditions.",
    },
    {
      id: "petition",
      kind: "clause",
      group: "Closing",
      cite: "Petition",
      label: "Petitioned for Redress",
      text: "In every stage of these Oppressions We have Petitioned for Redress in the most humble terms: Our repeated Petitions have been answered only by repeated injury. A Prince, whose character is thus marked by every act which may define a Tyrant, is unfit to be the ruler of a free people.",
    },
    {
      id: "brethren",
      kind: "clause",
      group: "Closing",
      cite: "British brethren",
      label: "Enemies in War, in Peace Friends",
      text: "Nor have We been wanting in attentions to our Brittish brethren. We have warned them from time to time of attempts by their legislature to extend an unwarrantable jurisdiction over us. We have reminded them of the circumstances of our emigration and settlement here. We have appealed to their native justice and magnanimity, and we have conjured them by the ties of our common kindred to disavow these usurpations, which, would inevitably interrupt our connections and correspondence. They too have been deaf to the voice of justice and of consanguinity. We must, therefore, acquiesce in the necessity, which denounces our Separation, and hold them, as we hold the rest of mankind, Enemies in War, in Peace Friends.",
    },
    {
      id: "therefore",
      kind: "clause",
      group: "Closing",
      cite: "Therefore",
      label: "Free and Independent States",
      text: "We, therefore, the Representatives of the united States of America, in General Congress, Assembled, appealing to the Supreme Judge of the world for the rectitude of our intentions, do, in the Name, and by Authority of the good People of these Colonies, solemnly publish and declare, That these United Colonies are, and of Right ought to be Free and Independent States; that they are Absolved from all Allegiance to the British Crown, and that all political connection between them and the State of Great Britain, is and ought to be totally dissolved; and that as Free and Independent States, they have full Power to levy War, conclude Peace, contract Alliances, establish Commerce, and to do all other Acts and Things which Independent States may of right do.",
    },
    {
      id: "pledge",
      kind: "clause",
      group: "Closing",
      cite: "Pledge",
      label: "Lives, Fortunes, and sacred Honor",
      text: "And for the support of this Declaration, with a firm reliance on the protection of divine Providence, we mutually pledge to each other our Lives, our Fortunes and our sacred Honor.",
    },
    {
      id: "signers-nh",
      kind: "signers",
      group: "Signers",
      cite: "New Hampshire",
      label: "Signers",
      text: "Josiah Bartlett\nWilliam Whipple\nMatthew Thornton",
    },
    {
      id: "signers-ma",
      kind: "signers",
      group: "Signers",
      cite: "Massachusetts",
      label: "Signers",
      text: "John Hancock\nSamuel Adams\nJohn Adams\nRobert Treat Paine\nElbridge Gerry",
    },
    {
      id: "signers-ri",
      kind: "signers",
      group: "Signers",
      cite: "Rhode Island",
      label: "Signers",
      text: "Stephen Hopkins\nWilliam Ellery",
    },
    {
      id: "signers-ct",
      kind: "signers",
      group: "Signers",
      cite: "Connecticut",
      label: "Signers",
      text: "Roger Sherman\nSamuel Huntington\nWilliam Williams\nOliver Wolcott",
    },
    {
      id: "signers-ny",
      kind: "signers",
      group: "Signers",
      cite: "New York",
      label: "Signers",
      text: "William Floyd\nPhilip Livingston\nFrancis Lewis\nLewis Morris",
    },
    {
      id: "signers-nj",
      kind: "signers",
      group: "Signers",
      cite: "New Jersey",
      label: "Signers",
      text: "Richard Stockton\nJohn Witherspoon\nFrancis Hopkinson\nJohn Hart\nAbraham Clark",
    },
    {
      id: "signers-pa",
      kind: "signers",
      group: "Signers",
      cite: "Pennsylvania",
      label: "Signers",
      text: "Robert Morris\nBenjamin Rush\nBenjamin Franklin\nJohn Morton\nGeorge Clymer\nJames Smith\nGeorge Taylor\nJames Wilson\nGeorge Ross",
    },
    {
      id: "signers-de",
      kind: "signers",
      group: "Signers",
      cite: "Delaware",
      label: "Signers",
      text: "Caesar Rodney\nGeorge Read\nThomas McKean",
    },
    {
      id: "signers-md",
      kind: "signers",
      group: "Signers",
      cite: "Maryland",
      label: "Signers",
      text: "Samuel Chase\nWilliam Paca\nThomas Stone\nCharles Carroll of Carrollton",
    },
    {
      id: "signers-va",
      kind: "signers",
      group: "Signers",
      cite: "Virginia",
      label: "Signers",
      text: "George Wythe\nRichard Henry Lee\nThomas Jefferson\nBenjamin Harrison\nThomas Nelson, Jr.\nFrancis Lightfoot Lee\nCarter Braxton",
    },
    {
      id: "signers-nc",
      kind: "signers",
      group: "Signers",
      cite: "North Carolina",
      label: "Signers",
      text: "William Hooper\nJoseph Hewes\nJohn Penn",
    },
    {
      id: "signers-sc",
      kind: "signers",
      group: "Signers",
      cite: "South Carolina",
      label: "Signers",
      text: "Edward Rutledge\nThomas Heyward, Jr.\nThomas Lynch, Jr.\nArthur Middleton",
    },
    {
      id: "signers-ga",
      kind: "signers",
      group: "Signers",
      cite: "Georgia",
      label: "Signers",
      text: "Button Gwinnett\nLyman Hall\nGeorge Walton",
    },
  ],
};
